### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by roliveira** [OPM/opm-data#3]
I was looking at these datasets and noticed that there isn't a file with the [Open Data License](https://opendatacommons.org/licenses/odbl/) text, only the mention to it in the `README.md`. There is also a `COPYING` file with the sleipner case, but that also does not contain the full license.

**Comment by alfbr** [comment]
Good point. There is a link to the license text in all headers for all files though. Your point still stands, ideally repositories should be self-contained with the license text explicitly available in the repository. A pull request is welcome, both here and in opm-tests ;-)

**Comment by atgeirr** [comment]
> There is also a `COPYING` file with the sleipner case, but that also does not contain the full license.

For the Sleipner data, the full license is in the license.pdf file. I agree we should put the ODL and ODBL licenses in here in text form, though.
